config/routes.rb
require File.join(Rails.root, 'lib', 'state')

Rails.application.routes.draw do
  resources :leads, only: [:new, :create]

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations' } 
  devise_scope :user do
    delete '/users/delete_headshot', to: 'registrations#delete_headshot', as: :delete_headshot
  end

  namespace :admin do

    resources :communities do
      collection do
        post :search
      end
      scope module: 'community_associations' do
        resources :pet_policies
        resources :photos
        resources :floorplans
        resources :attachments
        resources :community_dining
        resources :costs, only: [:index]
        resources :deposit_fees
        resources :other_services
      end
    end
    resources :users do 
      collection do
        get :search
        get :report
      end
    end
    resources :choice_collections, except: [:new]
    resources :choice_collection_communities, only: [:create, :destroy]
    resources :glossary_terms
    resources :geolocations, only: [:index]
    resources :tags, except: [:destroy] do
      member do 
        get :category_changed
      end
    end
    root to: 'dashboard#index'
  end

  resources :communities, except: [:index, :create] do
    collection do
      get :autocomplete
      post :map_search
    end
  end

  get '/:state/:city/:id', to: 'communities#show', as: :community_vanity, constraints: { state: State::REGEXP }

  resources :searches
  resources :notes
  resources :choice_collections, only: [:index, :show]
  
  get '/favorites', to: 'communities#favorites', as: :favorites
  post '/communities/:id/favorite', to: 'communities#favorite'
  post '/communities/:id/unfavorite', to: 'communities#unfavorite'

  get '/about', to: 'pages#about'

  get '/policy', to: 'pages#policy'

  get '/terms', to: 'pages#terms'

  get '/users/preregistration', to: 'users#preregistration'

  get '/users', to: 'pages#users'

  get '/user-show', to: 'pages#user_show'

  get '/dashboard', to: 'dashboard#index'

  root to: 'communities#index', via: [:get, :post]

  get '/popup', to: redirect('/')

  match '/:state/:city', to: 'communities#city_lander', via: [:get, :post], constraints: { state: State::REGEXP }
end

app/models/glossary_term.rb
class GlossaryTerm < ActiveRecord::Base
  validates :name, :description, :kind, presence: true
  validates_uniqueness_of :name

  has_many :community_glossary_terms
  has_many :communities, through: :community_glossary_terms
end

app/controllers/admin/glossary_terms_controller.rb
class Admin::GlossaryTermsController < Admin::Base

  before_action :require_admin
  
  def index
    @glossary_terms = GlossaryTerm.order(created_at: :desc).all
  end

  def new
    @glossary_term = GlossaryTerm.new
  end

  def create
    @glossary_term = GlossaryTerm.new(glossary_term_params)
    if @glossary_term.save
      redirect_to admin_glossary_terms_path
    else
      render action: :new, status: 422
    end
  end

  def edit
    @glossary_term = GlossaryTerm.find(params[:id])
  end

  def update
    @glossary_term = GlossaryTerm.find(params[:id])
    if @glossary_term.update_attributes(glossary_term_params)
      redirect_to admin_glossary_terms_path
    else
      render action: :edit, status: 422
    end
  end

  def destroy
    GlossaryTerm.find(params[:id]).delete
    redirect_to admin_glossary_terms_path
  end

private

  def glossary_term_params
    params.require(:glossary_term).permit([:name, :kind, :description])
  end 
end

app/views/admin/glossary_terms/_form.html.slim
= simple_form_for [:admin, @glossary_term] do |f|
  .section
    .section
      = f.input :name, label: 'Name'
      = f.input :kind, input_html: { value: 'care charge' }
      = f.input :description
      = f.submit 'Save'

app/views/admin/glossary_terms/edit.html.slim
.content_page.community_edit
  p 
    span.icon_back.sprite
    = link_to 'Back to Glossary Terms', admin_glossary_terms_path

  h1 
    | Glossary Term&nbsp;-&nbsp;
    = @glossary_term.name

  = render 'form'

app/views/admin/glossary_terms/index.html.slim
.content_page.community_edit
  p 
    span.icon_back.sprite
    = link_to 'Back to Admin', admin_root_path

  h1 Glossary Terms

  .section.borderless  
    h2 = link_to 'Add New', new_admin_glossary_term_path, class: 'button'

    ul.costs_list
      - @glossary_terms.each do |gt|
        li
          ul
            li
              strong= "#{gt.name || '-'}"
              | &nbsp;-&nbsp;
              span = link_to 'Edit', edit_admin_glossary_term_path(gt)
              |&nbsp;|&nbsp;
              span = link_to 'Delete', admin_glossary_term_path(gt), 'data-method' => :delete, 'data-confirm' => 'Are you sure?'
            li= "Description: #{gt.description || '-'}"

app/views/admin/glossary_terms/new.html.slim
.content_page.community_edit
  p 
    span.icon_back.sprite
    = link_to 'Back to Glossary Terms', admin_glossary_terms_path

  h1 New Glossary Term

  = render 'form'