config/routes.rb
require File.join(Rails.root, 'lib', 'state')

Rails.application.routes.draw do
  resources :leads, only: [:new, :create]

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations' } 
  devise_scope :user do
    delete '/users/delete_headshot', to: 'registrations#delete_headshot', as: :delete_headshot
  end

  namespace :admin do

    resources :communities do
      collection do
        post :search
      end
      scope module: 'community_associations' do
        resources :pet_policies
        resources :photos
        resources :floorplans
        resources :attachments
        resources :community_dining
        resources :costs, only: [:index]
        resources :deposit_fees
        resources :other_services
      end
    end
    resources :users do 
      collection do
        get :search
        get :report
      end
    end
    resources :choice_collections, except: [:new]
    resources :choice_collection_communities, only: [:create, :destroy]
    resources :glossary_terms
    resources :geolocations, only: [:index]
    resources :tags, except: [:destroy] do
      member do 
        get :category_changed
      end
    end
    root to: 'dashboard#index'
  end

  resources :communities, except: [:index, :create] do
    collection do
      get :autocomplete
      post :map_search
    end
  end

  get '/:state/:city/:id', to: 'communities#show', as: :community_vanity, constraints: { state: State::REGEXP }

  resources :searches
  resources :notes
  resources :choice_collections, only: [:index, :show]
  
  get '/favorites', to: 'communities#favorites', as: :favorites
  post '/communities/:id/favorite', to: 'communities#favorite'
  post '/communities/:id/unfavorite', to: 'communities#unfavorite'

  get '/about', to: 'pages#about'

  get '/policy', to: 'pages#policy'

  get '/terms', to: 'pages#terms'

  get '/users/preregistration', to: 'users#preregistration'

  get '/users', to: 'pages#users'

  get '/user-show', to: 'pages#user_show'

  get '/dashboard', to: 'dashboard#index'

  root to: 'communities#index', via: [:get, :post]

  get '/popup', to: redirect('/')

  match '/:state/:city', to: 'communities#city_lander', via: [:get, :post], constraints: { state: State::REGEXP }
end

app/models/user.rb
class User < ActiveRecord::Base
  TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX = /\Achange@me/

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  validates_format_of :email, :without => TEMP_EMAIL_REGEX, on: :update
  validates_presence_of :phone
  validates_presence_of :first_name
  validates_presence_of :last_name

  searchkick word_start: [:first_name, :last_name, :phone, :email]

  enum role: [:user, :admin, :advocate]

  attr_accessor :send_invitation_email

  has_many :managed_collections, class_name: "ChoiceCollection", foreign_key: "admin_id"
  has_many :choice_collections
  has_many :favorites
  has_many :notes
  has_many :searches
  
  include Headshot

  def search_data
    self.as_json(only: [:email, :role, :first_name, :last_name, :email, :phone])
  end

  def set_password_reset_token
    raw_token, hashed_token = Devise.token_generator.generate(self.class, :reset_password_token)

    self.password = SecureRandom.hex
    self.reset_password_sent_at = Time.now.utc
    self.reset_password_token = hashed_token
    self.save(validate: false)

    return raw_token
  end

  def has_previously_logged_in?
    self.sign_in_count.to_i > 0
  end

  def self.find_for_oauth(auth, signed_in_resource = nil)

    # Get the identity and user if they exist
    identity = Identity.find_for_oauth(auth)

    # If a signed_in_resource is provided it always overrides the existing user
    # to prevent the identity being locked with accidentally created accounts.
    # Note that this may leave zombie accounts (with no associated identity) which
    # can be cleaned up at a later date.
    user = signed_in_resource ? signed_in_resource : identity.user

    # Create the user if needed
    if user.nil?

      # Get the existing user by email if the provider gives us a verified email.
      # If no verified email was provided we assign a temporary email and ask the
      # user to verify it on the next step via UsersController.finish_signup
      email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
      email = auth.info.email if email_is_verified
      user = User.where(:email => email).first if email

      # Create the user if it's a new registration
      if user.nil?
        user = User.new(
          #username: auth.info.nickname || auth.uid,
          email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
          password: Devise.friendly_token[0,20]
        )
        user.save!
      end
    end

    # Associate the identity with the user if needed
    if identity.user != user
      identity.user = user
      identity.save!
    end
    user
  end

  def email_verified?
    self.email && self.email !~ TEMP_EMAIL_REGEX
  end

  def name_or_email 
    if first_name && last_name
      "#{first_name} #{last_name}" 
    else
      email
    end
  end

  def internal?
    self[:role] > 0
  end

  def self.create_user_from_lead(first_name, last_name, email, phone)
    @raw_token, hashed_token = Devise.token_generator.generate(User, :reset_password_token)
    @user = User.create({
                first_name: first_name,
                 last_name: last_name,
                     email: email,
                     phone: phone,
                  password: SecureRandom.hex,
    reset_password_sent_at: Time.now.utc,
      reset_password_token: hashed_token,
                  external: true,
                       })
  end
end

app/views/shared/_footer.html.slim
#footer Footer

app/views/shared/_google_analytics.html.slim
javascript:
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-38856434-2', 'auto');
  ga('send', 'pageview');

app/views/shared/_header.html.slim
-if current_user
  input type="hidden" id="user-exists" value="true"
#header
  a#logo.sprite href="/"
  
  p.headline 
    span.break_box Our Free, Personalized Service Helps Thousands of Atlanta Area Families.&nbsp;
    span.break_box 
      ' Talk to a Local Senior Housing and Care Expert Now: 
      span.phone
        | (404) 334-5500

  ul#login_links
    li.login_link_box.logged_out

      a.link_price_estimate.lead_form_trigger id="lead_form_00_results_2" data-phone='(404) 334-5500' data-title="Get Expert Help"  data-for="check_availability_form" title="Get Expert Help" href="javascript:void(0);"
        | Get Expert Help

    li.login_link_box.logged_out
      a href="/users/sign_up" Join
    li.login_link_box.logged_out
      a href="/users/sign_in" Log in
    li.logged_in
      a href="/dashboard" Your Family Account
    li.logged_in 
      a href="/favorites" Favorites     
    
      
  ul#nav
    li.nav_level1
      a href="javascript:void(0);"
        span.icon_menu.sprite
        span.link_text More
      ul.nav_level2
        - if current_user.try(:internal?)
          li
            a href="/admin" Admin
        li.logged_out.login_link_box 
          a href="/users/sign_up" Join Now
        li.logged_in.login_link_box 
          a href="/dashboard" Family Account
        li.logged_in.login_link_box 
          a href="/favorites" Favorites
        / li.logged_in
        /   a href="/dashboard" Dashboard 
        li.logged_in.construction
          a href="#" Choice Collection
        /li 
        /  a href="/about" About Us
        li 
          a href="/policy" Privacy Policy 
        / li.logged_in
        /   a href="/users/edit" Account
        li.logged_in
          a href="/users/sign_out" Log Out


  a#map_switch.construction href="javascript:void(0);" Map

app/views/shared/_header_admin.html.slim
#header
  a#logo.sprite href="/"
  - if @choice_collection  && params[:edit]
    - u = @choice_collection.user
    #choice_collection_data style="display:none;" data-id=@choice_collection.id data-community-data=@choice_collection.choice_collection_communities.map{|x| { community_id: x.community_id, notes: x.notes.last.try(:body), name: @choice_collection.advocate.try(:name_or_email) || @choice_collection.admin.name_or_email } }.to_json
    p.headline 
      span.break_box Editing&nbsp;
      span.collection_name 
        =@choice_collection.name
      | &nbsp;
      ' for 
      span.break_box.collection_user_name 
        -if u.first_name || u.last_name
          = link_to "#{u.first_name} #{u.last_name}", admin_user_path(u), :title=>'View User Profile'
        -else
          = link_to "#{u.email}", admin_user_path(u)
      span.choice_collection_links.break_box
        | &nbsp; - &nbsp;
        =link_to "Rename", "javascript:void(0)", :class=>"edit_cc_name", :title=>'Rename this Choice Collection', 'data-name'=>@choice_collection.name
        |&nbsp; | &nbsp;
        =link_to "Review", admin_choice_collection_path(@choice_collection), :title=>'Review & Send this Choice Collection to the User'

  ul#login_links
    li.login_link_box.logged_out
      a href="/users/sign_in" Login
    li.logged_in
      a href="/admin" Dashboard   
    li.logged_in
      a href="/users/sign_out" Log Out

  ul#nav
    li.nav_level1
      a href="javascript:void(0);" 
        span.icon_menu.sprite
      ul.nav_level2
        - if current_user.try(:admin?)
          li
            a href="/admin" Dashboard

        li.logged_in
          a href=admin_communities_path Search Communities
        li.logged_in
          a href=admin_users_path Search Users
        li.logged_in
          a href=admin_choice_collections_path Choice Collections
        li.logged_in
          a href=admin_glossary_terms_path Glossary Editor
        li.logged_in
          a href=admin_tags_path Features Editor

        li.logged_in
          a href="/users/edit" Account
          // a href="/users/edit" #{current_user.email}

        li.logged_in.login_link_box 
          a href="/users/edit" Account
        li.logged_in.login_link_box 
          a href="/users/sign_out" Log Out

app/views/shared/_price_options.html.slim
#options_price.options_group_box
  span.title Monthly Cost
  .options_group
    span.box
      label for="price_min_option" Min. Price
      select id="price_min_option" name="price[min]"
        option selected=(@search['price'].try(:[], 'min')=="0" ? "" : nil) value="0" $0
        
        - (1000..9000).step(1000).each do |num|
          option selected=(@search['price'].try(:[], 'min')==num.to_s ? "" : nil) value=num =cost(num)

        option selected=(@search['price'].try(:[], 'min')=="100000" ? "" : nil) value="100000" $10,000+

    span.box
      label for="price_max_option" Max. Price
      select id="price_max_option" name="price[max]"
        option selected=(@search['price'].try(:[], 'max')=="100000" ? "" : nil) value="100000" $10,000+

        - 9000.step(1000,-1000) do |num|
          option selected=(@search['price'].try(:[], 'max')==num.to_s ? "" : nil) value=num =cost(num)

    .clr

app/views/shared/_result.html.slim
#total_result_count.hidden=@results.total_count

- (@matched_results.to_a + @results.to_a).each do |result|
  .result id=result.id data-attributes=result.to_json data-url=community_path(result) class=favorites_class(result)
    span.map_active_arrow
      span.arrow_pointer
    span.favorite_box
      span.icon_favorite.sprite title="Add to Favorites"

    .box1
      .image_box
        = link_to(community_image(result.hero_image, small: true, :class=> 'details_link'), community_path(result), :class=>'details_link')
    
    .box2
      .category= result.care_types.join(' | ')
      .title
        =link_to result.name, community_path(result), class: 'details_link'
      
      span.address
        span.address1
          ==result.address
        span.seperator &nbsp; - &nbsp;
        span.address2 
          =get_location_string(result)

      .cta_box
        .box
          span.phone 
            == phone_number(result)
        .box.box2
          a.link_check_availability.lead_form_trigger id="lead_form_#{result.id}_results_0" data-phone=raw_phone_number(result) data-title="Check Availability" data-community-id=result.id data-for="check_availability_form" title="Check Availability" 
            span.icon_expand.sprite
            | Check Availability
          a.link_schedule_tour.lead_form_trigger id="lead_form_#{result.id}_results_1" data-phone=raw_phone_number(result) data-title="Schedule a Tour" data-community-id=result.id data-for="check_availability_form" title="Schedule a Tour" 
            span.icon_expand.sprite
            | Schedule a Tour
          a.link_price_estimate.lead_form_trigger id="lead_form_#{result.id}_results_2" data-phone=raw_phone_number(result) data-title="Get a Price Estimate" data-community-id=result.id data-for="check_availability_form" title="Get a Price Estimate" 
            span.icon_expand.sprite
            | Get an Estimate
        .clr
          
      span.price
        - if result.starting_at.to_i != 0
          | Starting at 
          = cost(result.starting_at)
          span.small_text 
            | /mo.

      span.link_details
        =link_to 'View Photos, Floorplans, Pricing & More', community_path(result), class: 'details_link'
      .clr

    - if (@note_ids || []).include?(result.id)
      .notes
        a.view_detail_notes.link_notes_big.details_link href="javascript:void(0);" title="View Advocate Notes on this Community"
          span.icon_notes.sprite
          | Advocate Notes
        span.link_notes_big &nbsp;-&nbsp;  
        a.view_detail_notes.link_notes_big.details_link href="javascript:void(0);" title="View My Notes on this Community"
          | My Notes
        span.link_notes_big &nbsp;-&nbsp;
        a.view_detail_notes.link_notes_big.details_link href="javascript:void(0);" title="Add a Note on this Community"
          | Add a Note
        a.view_detail_notes.link_notes_small.details_link href="javascript:void(0);" title="View/Add Notes on this Community" 
          span.icon_notes.sprite
          | Notes
    .clr

#infinite_scrolling
  =will_paginate @results

#special_margin

app/views/shared/_search_box.html.slim
#search_box
  form#search_form action=root_path method="POST"
    input name="authenticity_token" value=form_authenticity_token type="hidden"
    input name="sort" value=(@search['sort'] || "distance") type="hidden"

    ul#search_tabs.tabs style="display:none"
      li#tab_housing.active
        a href="javascript:void(0);" 
          | Senior Care
          br
          | Communities
      li#tab_at_home
        a href="javascript:void(0);" 
          | Senior Care
          br
          | at Home
      li#tab_resources
        a href="javascript:void(0);" 
          | Family &amp; Senior
          br
          | Resources

    #search_intro_box
      #intro_housing.search_intro.active  Find Assisted Living, Independent Living, Memory Care
      #intro_at_home.search_intro  Find Home Care, Hospice, Adult Day, Home Health
      #intro_resources.search_intro  Find Legal, Financial, Insurance
    #search_field_holder.auto_complete_box 
      #search_field_box data-url=root_path

        input type='text' id='communities-autocomplete-input' data-url=autocomplete_communities_path placeholder="Search City, Zip, or Community Name" name="term" autocomplete="off" class="auto_complete_in" value=@search['term']

        input#search_kind type='hidden' name='kind' value=@search['kind']
        //ul#search_channels
          //li.search_channel Type

        / a.btn_search.btn_cta.button href="#" 
        /   span.icon_search.sprite

      / a#search_tip.link_tooltip href="javascript:void(0);" 
      /   span.link_text ? 
      /   span.tooltip.right
      /     span.tooltip_title Tooltip Title
      /     span.tooltip_paragraph Tooltip text paragraph looks like this. Tooltip text paragraph looks like this. Tooltip text paragraph looks like this.
      /     span.tooltip_paragraph Tooltip text paragraph looks like this. Tooltip text paragraph looks like this. Tooltip text paragraph looks like this. 

      #communities-autocomplete-output.auto_complete_out

    #search_options

      .options_box
        #search_housing.options_group_box
          span.title Choose Community Type(s)
          .options_group
            - if @search.blank?
              span.box
                input type="checkbox" checked="" name="community_type[Independent Living]" id="comm_type_il_option"
                label for="comm_type_il_option" Independent Living
              span.box
                input type="checkbox" checked="" name="community_type[Assisted Living]" id="comm_type_al_option"
                label for="comm_type_al_option" Assisted Living
              span.box
                input type="checkbox" checked="" name="community_type[Memory Care]" id="comm_type_mc_option"
                label for="comm_type_mc_option" Memory Care
            - else
              span.box
                input type="checkbox" checked=(@search['community_type']['Independent Living'] == 'on' ? "" : nil) name="community_type[Independent Living]" id="comm_type_il_option"
                label for="comm_type_il_option" Independent Living
              span.box
                input type="checkbox" checked=(@search['community_type']['Assisted Living'] == 'on' ? "" : nil) name="community_type[Assisted Living]" id="comm_type_al_option"
                label for="comm_type_al_option" Assisted Living
              span.box
                input type="checkbox" checked=(@search['community_type']['Memory Care'] == 'on' ? "" : nil) name="community_type[Memory Care]" id="comm_type_mc_option"
                label for="comm_type_mc_option" Memory Care
            / span.box
            /   input type="checkbox" checked="" name="community_type[Residential Care Home]" id="comm_type_rch_option"
            /   label for="comm_type_rch_option" Residential Care Home
            / span.box
            /   input type="checkbox" checked="" name="community_type[Continuing Care]" id="comm_type_ccrc_option"
            /   label for="comm_type_ccrc_option" Continuing Care (CCRC)
            / span.box
            / span.box
            /   input type="radio" name="care_types_radio" value="community_type[nursing home rehab]" id="comm_type_nhr_option"
            /   label for="comm_type_nhr_option" Nursing Home/Rehab
            / span.box
            /   input type="radio" name="care_types_radio" value="community_type[hospice]" id="comm_type_hospice_option"
            /   label for="comm_type_hospice_option" Hospice (In-Patient)
            .clr

          #advanced_search_box.hidden
            #options_beds.options_group_box
              span.title Bedrooms
              .options_group
                - if @search.blank?
                  span.box
                    input type="checkbox" checked="" name="beds[shared]" id="br_shared_option"
                    label for="br_shared_option" Shared 
                  span.box
                    input type="checkbox" checked="" name="beds[studio]" id="br_studio_option"
                    label for="br_studio_option" Studio
                  span.box
                    input type="checkbox" checked="" name="beds[1 bedroom]" id="br_1br_option"
                    label for="br_1br_option" 1 Bedroom
                  span.box
                    input type="checkbox" checked="" name="beds[2 bedroom]" id="br_2br_option"
                    label for="br_2br_option" 2 Bedrooms
                  span.box
                    input type="checkbox" checked="" name="beds[3 bedroom]" id="br_3br_option"
                    label for="br_3br_option" 3 Bedrooms
                - else
                  span.box
                    input type="checkbox" checked=(@search['beds']['shared'] == 'on' ? "" : nil) name="beds[shared]" id="br_shared_option"
                    label for="br_shared_option" Shared 
                  span.box
                    input type="checkbox" checked=(@search['beds']['studio'] == 'on' ? "" : nil) name="beds[studio]" id="br_studio_option"
                    label for="br_studio_option" Studio
                  span.box
                    input type="checkbox" checked=(@search['beds']['1 bedroom'] == 'on' ? "" : nil) name="beds[1 bedroom]" id="br_1br_option"
                    label for="br_1br_option" 1 Bedroom
                  span.box
                    input type="checkbox" checked=(@search['beds']['2 bedroom'] == 'on' ? "" : nil) name="beds[2 bedroom]" id="br_2br_option"
                    label for="br_2br_option" 2 Bedrooms
                  span.box
                    input type="checkbox" checked=(@search['beds']['3 bedroom'] == 'on' ? "" : nil) name="beds[3 bedroom]" id="br_3br_option"
                    label for="br_3br_option" 3 Bedrooms
                / span.box
                /   input type="checkbox" checked="" name="beds[cottage]" id="br_cottage_option" 
                /   label for="br_cottage_option" Cottage
                .clr

            = render 'shared/price_options'

            #options_pets.options_group_box
              span.title Pets
              .options_group
                
                span.box
                  input type="checkbox" name="tags[dogs allowed]" id="pets_dogs_option" checked=(@search['tags'].try(:[], 'dogs allowed') == "on" ? "" : nil)
                  label for="pets_dogs_option" Dogs Allowed
                span.box
                  input type="checkbox" name="tags[cats allowed]" id="pets_cats_option" checked=(@search['tags'].try(:[], 'cats allowed') == "on" ? "" : nil)
                  label for="pets_cats_option" Cats Allowed
                .clr
            
          
        #search_at_home.options_group_box.hidden
          .options_group
            span.title Choose Service Type(s)
            span.box
              input type="checkbox" checked=""
              label Home Care
            span.box
              input type="checkbox" checked=""
              label Home Health Care
            span.box
              input type="checkbox" checked=""
              label Hospice at Home
            span.box
              input type="checkbox" checked=""
              label Adult Day Care
            span.box
              input type="checkbox" checked=""
              label Senior Center
            .clr

        #search_resources.options_group_box.hidden
          .options_group
            span.title Choose Resource Type(s)
            span.box
              input type="checkbox" checked=""
              label Financial Planning
            span.box
              input type="checkbox" checked=""
              label Elder Law
            span.box
              input type="checkbox" checked=""
              label Senior Insurance
            span.box
              input type="checkbox" checked=""
              label Aging Agency
            span.box
              input type="checkbox" checked=""
              label Care Giver Support
            span.box
              input type="checkbox" checked=""
              label Health Care Supplies
            span.box
              input type="checkbox" checked=""
              label Final Planning
            span.box
              input type="checkbox" checked=""
              label Senior Transitions Services
            span.box
              input type="checkbox" checked=""
              label Home Accessibility Contractors
            span.box
              input type="checkbox" checked=""
              label Professional Organizations
            span.box
              input type="checkbox" checked=""
              label Long Term Care Planning
            span.box
              input type="checkbox" checked=""
              label Senior Technical Services
            span.box
              input type="checkbox" checked=""
              label Employment Services
            span.box
              input type="checkbox" checked=""
              label Realtors
            .clr

      .clr
      .button_box 
        .box.text_align_left.search_bottom_links
          a#cancel_search_link href="javascript:void(0);" Cancel
          a#link_advanced_search href="javascript:void(0);" More Options
        .box.text_align_right
          input#btn_search.button.btn_cta.btn_large.btn_search type="submit" value="Search"
        .clr
      h2.call_for_help 
        span.break_box 
          ' Can't find the right service?
        span.break_box 
          ' Call us today 
        span.break_box.phone 
          | (404) 334-5500
    .clr

app/views/shared/_snapengage.html.slim
javascript:
  (function() {
    var se = document.createElement('script'); se.type = 'text/javascript'; se.async = true;
    se.src = '//commondatastorage.googleapis.com/code.snapengage.com/js/e40f7247-a363-4b58-8b8c-a6eaff5fce9b.js';
    var done = false;
    se.onload = se.onreadystatechange = function() {
      if (!done&&(!this.readyState||this.readyState==='loaded'||this.readyState==='complete')) {
        done = true;
        /* Place your SnapEngage JS API code below */
        /* SnapEngage.allowChatSound(true); Example JS API: Enable sounds for Visitors. */
        var seAgent;
        SnapABug.setCallback('OpenProactive', function(agent, msg) {
            seAgent = agent;
            _gaq.push(['_trackEvent', 'SnapEngage', 'proactivePrompt', agent]);
        });
         
        SnapABug.setCallback('StartChat', function(email, msg, type) {
            if (type == 'proactive') {
                _gaq.push(['_trackEvent', 'SnapEngage', 'proactiveEngaged', seAgent]);
            }
        });
      }
    };
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(se, s);
  })();

app/views/shared/_spinner.html.slim
.spinner_box
	.spinner
	  .bar1
	  .bar2
	  .bar3
	  .bar4
	  .bar5
	  .bar6
	  .bar7
	  .bar8
	  .bar9
	  .bar10
	  .bar11
	  .bar12