config/routes.rb
require File.join(Rails.root, 'lib', 'state')

Rails.application.routes.draw do
  resources :leads, only: [:new, :create]

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations' } 
  devise_scope :user do
    delete '/users/delete_headshot', to: 'registrations#delete_headshot', as: :delete_headshot
  end

  namespace :admin do

    resources :communities do
      collection do
        post :search
      end
      scope module: 'community_associations' do
        resources :pet_policies
        resources :photos
        resources :floorplans
        resources :attachments
        resources :community_dining
        resources :costs, only: [:index]
        resources :deposit_fees
        resources :other_services
      end
    end
    resources :users do 
      collection do
        get :search
        get :report
      end
    end
    resources :choice_collections, except: [:new]
    resources :choice_collection_communities, only: [:create, :destroy]
    resources :glossary_terms
    resources :geolocations, only: [:index]
    resources :tags, except: [:destroy] do
      member do 
        get :category_changed
      end
    end
    root to: 'dashboard#index'
  end

  resources :communities, except: [:index, :create] do
    collection do
      get :autocomplete
      post :map_search
    end
  end

  get '/:state/:city/:id', to: 'communities#show', as: :community_vanity, constraints: { state: State::REGEXP }

  resources :searches
  resources :notes
  resources :choice_collections, only: [:index, :show]
  
  get '/favorites', to: 'communities#favorites', as: :favorites
  post '/communities/:id/favorite', to: 'communities#favorite'
  post '/communities/:id/unfavorite', to: 'communities#unfavorite'

  get '/about', to: 'pages#about'

  get '/policy', to: 'pages#policy'

  get '/terms', to: 'pages#terms'

  get '/users/preregistration', to: 'users#preregistration'

  get '/users', to: 'pages#users'

  get '/user-show', to: 'pages#user_show'

  get '/dashboard', to: 'dashboard#index'

  root to: 'communities#index', via: [:get, :post]

  get '/popup', to: redirect('/')

  match '/:state/:city', to: 'communities#city_lander', via: [:get, :post], constraints: { state: State::REGEXP }
end

app/models/choice_collection.rb
class ChoiceCollection < ActiveRecord::Base
  has_many :choice_collection_communities
  has_many :communities, through: :choice_collection_communities
  belongs_to :admin, class_name: "User", foreign_key: "admin_id"
  belongs_to :user
  belongs_to :advocate, class_name: "User", foreign_key: "advocate_user_id"

  # validates_presence_of :personal_message, allow_nil: false, allow_blank: false

  def owner
    self.advocate || self.admin
  end
end

app/controllers/admin/choice_collections_controller.rb
class Admin::ChoiceCollectionsController < Admin::Base

  append_view_path("#{Rails.root}/app/views/mailers")

  def index
    @choice_collections = ChoiceCollection.where(admin_id: current_user.id).order(created_at: :desc).all
  end

  def show
    @sent = params[:sent]
    @choice_collection = ChoiceCollection.find(params[:id])
    set_email_fields
  end

  def create
    @choice_collection = ChoiceCollection.new(choice_collection_params)
    @choice_collection.name = "Choice Collection #1"
    set_email_fields
    if @choice_collection.save(validate: false)
      session[:choice_collection_id] = @choice_collection.id
      redirect_to admin_communities_path(edit: true)
    else
      render action: :show, status: 422
    end
  end

  def edit
    @choice_collection = ChoiceCollection.find(params[:id])
    session[:choice_collection_id] = @choice_collection.id
    redirect_to admin_communities_path(edit:true)
  end

  def update
    @choice_collection = ChoiceCollection.find(params[:id])
    if @choice_collection.update_attributes(choice_collection_params)

      # make sure no email fields are blank
      set_email_fields
      @choice_collection.save(validate: false)

      # not just a normal save, save and deliver
      if params[:deliver]

        # final validation check that the personal message exists before sending
        if @choice_collection.personal_message.blank?
          @choice_collection.errors[:personal_message] = "can't be blank"
          render action: :show, status: 422
          return
        end

        deliver!
        flash[:popup] = "Choice collection sent!"
        redirect_to admin_user_path(@choice_collection.user)
      else
        redirect_to admin_choice_collection_path(@choice_collection)
      end
    else
      render action: :show, status: 422
    end
  end

  def destroy
    cc = ChoiceCollection.find(params[:id])
    user = cc.user
    cc.delete
    session[:choice_collection_id] = nil
    redirect_to admin_user_path(user)
  end

private

  def deliver!
    @choice_collection.update_attributes(sent: true, sent_on: DateTime.now)

    unless params[:deliver][:registration_only]
      cc_link = if @choice_collection.user.has_previously_logged_in?
        choice_collection_path(@choice_collection)
      else
        choice_collection_path(@choice_collection, token: @cc.user.set_password_reset_token)
      end
      UserChoiceCollectionMailer.choice_collection(@choice_collection, "http://www.assistedchoice.com#{cc_link}").deliver_now
    end

    unless params[:deliver][:collection_only]
      @choice_collection.communities.each do |comm|
        CommunityRegistrationMailer.registration(@choice_collection, comm).deliver_now unless comm.email.blank?
      end
    end
  end

  def set_email_fields
    @cc = @choice_collection

    @cc.personal_message = render_to_string(partial: 'choice_collections/default_personal_message', layout: false) if @cc.personal_message.blank?

    @cc.user_email_subject = 'Your Personalized Choice Collection is Ready for Review' if @cc.user_email_subject.blank?
    @cc.user_email_body = render_to_string(partial: 'user_choice_collection_mailer/body', layout: false) if @cc.user_email_body.blank?
    @cc.user_email_sig = render_to_string(partial: 'user_choice_collection_mailer/sig', layout: false) if @cc.user_email_sig.blank?

    @cc.comm_email_subject = "AssistedChoice Client Registration - {{community name will go here}}" if @cc.comm_email_subject.blank?
    @cc.comm_email_body = render_to_string(partial: 'community_registration_mailer/body', layout: false) if @cc.comm_email_body.blank?
    @cc.comm_email_sig = render_to_string(partial: 'community_registration_mailer/sig', layout: false) if @cc.comm_email_sig.blank?
  end

  def choice_collection_params
    parameters = params.require(:choice_collection).permit([:user_id, :name, :sent, :sent_on, :advocate_user_id, :personal_message, :user_email_subject, :user_email_body, :user_email_sig, :comm_email_subject, :comm_email_body, :comm_email_sig])
    parameters.merge(admin_id: current_user.id)
  end 

end

app/controllers/choice_collections_controller.rb
class ChoiceCollectionsController < ApplicationController

  def index
    force_login
    @choice_collections = current_user.choice_collections # TODO: where(sent: true) or something like that
  end

  def show
    @choice_collection = ChoiceCollection.find(params[:id])

    if current_user.nil?
      if @choice_collection.user.has_previously_logged_in?
        # returning user with password set, force them to login
        force_login
      elsif params[:token]
        # new account that has never logged in, need to set a password
        session[:previous_url] = request.fullpath
        redirect_to edit_user_password_path(reset_password_token: params[:token], cc_id: params[:id])
      end
      return
    end

    @favorite_ids = current_user.favorites.pluck(:community_id) # still need this in case they fav'd these
    @note_ids = current_user ? Note.where(user_id: current_user.id).pluck(:community_id) : []
    @search = {}
    
    unless current_user.internal?
      @choice_collection = current_user.choice_collections.find(params[:id])
    end

    @choice_ids = @choice_collection.communities.pluck(:community_id)
    @results = Community.search "*", { where:{ id: @choice_ids }, load: false }
    if @choice_collection.user_id == current_user.id
      UserViewedCcMailer.viewed(@choice_collection).deliver_now
      @choice_collection.update_attribute(:viewed, true)
    end
    render template: '/communities/index'
  end



end

app/views/admin/choice_collections/index.html.slim
.content_page.community_edit
  #choice_collections_list
    h1 
      | My Choice Collections
    h2
      a.button href="/admin/users/" Create New
    ul
      - for cc in @choice_collections
  	    li
          = link_to cc.name, choice_collection_path(cc), class: 'collection_name', target: '_blank', title: 'View this Choice Collection as a User'
          ' 
          span 
           ' &nbsp;for
          span
            = link_to "#{cc.user.first_name} #{cc.user.last_name}", admin_user_path(cc.user), title: "View User Profile", class: 'collection_user'
            '
          span
            | &nbsp; - &nbsp;
            -if cc.sent
              ' Sent on
              span.js_time=cc.sent_on.to_i
            -else
              ' Edited on
              span.js_time=cc.updated_at.to_i
          span.break_box
            | &nbsp; - &nbsp;
            / = link_to 'Delete', admin_choice_collections_path, method: :delete, 'data-confirm' => 'Are you sure you want to delete this Choice Collection?', :title=>'Delete this Choice Collection'
            /| &nbsp; | &nbsp;
            = link_to 'Edit', edit_admin_choice_collection_path(cc), title: 'Add, Remove Properties'
            | &nbsp; | &nbsp;
            = link_to 'Review & Send', admin_choice_collection_path(cc), title: 'Review & Send this Choice Collection to the User'

app/views/admin/choice_collections/show.html.slim
#choice_collection_list.content_page
  -if @sent
    .message 
      p 
        ' You have sent the following choice collection to 
        strong=@choice_collection.user.email
      .clr
  h1
    =@choice_collection.name
    span.choice_collection_links.break_box
        | &nbsp; - &nbsp;
        =link_to "Rename", "javascript:void(0)", class: "edit_cc_name", title: "Rename this Choice Collection",'data-name' => @choice_collection.name
        | &nbsp; | &nbsp;
        = link_to 'Edit', edit_admin_choice_collection_path(@choice_collection), title: 'Add, Remove Properties'
        | &nbsp; | &nbsp;
        = link_to 'Preview', choice_collection_path(@choice_collection), target: '_blank', title: "View choice collection as the user would see it"
  p.choice_collection_subtitle 
    ' A Choice Collection for
    = link_to "#{@choice_collection.user.first_name} #{@choice_collection.user.last_name}", admin_user_path(@choice_collection.user), :title=>"View User Profile"

  -@choice_collection.choice_collection_communities.each do |cccomm|
    .section
      h2 
        =link_to cccomm.community.name, community_path(cccomm.community), :target=>"_blank", :title=>"View this Choice Collection as a User"
      p.edit_links
        =link_to "Add Note", "javascript:void(0)", :class=>"choice_collection_note", :id=>cccomm.id, :title=>"Add Note for this Property"
        |&nbsp; | &nbsp;
        =link_to "Remove Property", admin_choice_collection_community_path(cccomm, :community_id=>cccomm.community.id),method: :delete, 'data-confirm' => 'Are you sure you want to remove this property from the Choice Collection?', :remote=>true, :class=>"remove_community",:title=>"Delete this Property from Choice Collection"
      p.note
        strong
          p.highlighted
            | Advocate Notes:&nbsp;
        -cccomm.notes.order("created_at desc").each do |note|
          p.note_added_by 
            =note.created_at.strftime("%m/%d/%Y")
            ' &nbsp;-
            = link_to 'Delete', note_path(note, choice_collection_id: params[:id]), method: :delete, 'data-confirm' => 'Delete this note?'
          p.note
            =note.try(:body)
          

      p.note
        strong
          p.highlighted.note_user_name
            =@choice_collection.user.name_or_email
            |'s Notes:&nbsp;
        -@choice_collection.user.notes.where(admin_id: nil).where(:community_id=>cccomm.community_id).order("created_at desc").each do |note|
          p.note_added_by =note.created_at.strftime("%m/%d/%Y")
          p.note
            =note.try(:body)
              
      p.registrations
        strong
          | Registrations Delivered To:&nbsp;
        =cccomm.community.email || "No Contact E-mail Available"
      


  = simple_form_for [:admin, @choice_collection], :url=>admin_choice_collection_path(@choice_collection), :method=>:patch do |f|
    .section
      h2 
        | Edit Details
      = f.input :advocate_user_id, collection: User.where("role IN (1, 2)").map {|x| [x.name_or_email, x.id ]}, label: 'Send From', include_blank: false, selected: @choice_collection.advocate_user_id || current_user.id
      = f.input :personal_message, label: '* Personal Message', input_html: { class: 'redactor' }
      = f.submit 'Save Message', class: 'button btn_cta'

    .section
      h2 Edit User Email
      = f.input :user_email_subject, label: 'User Email Subject'
      = f.input :user_email_body, label: 'User Email Body', input_html: { class: 'redactor' }
      = f.input :user_email_sig, label: 'User Email Signature', input_html: { class: 'redactor' }
      = f.submit 'Save User Email', class: 'button btn_cta'

    /.section
      /h2
      /  | Edit Community Registration Email
      = f.input :comm_email_subject, label: 'Community email subject', as: :hidden
      = f.input :comm_email_body, label: 'Community email body', as: :hidden
      = f.input :comm_email_sig, label: 'Community email signature', as: :hidden
      /= f.submit 'Save Registration Email', class: 'button btn_cta'

    .button_box.text_align_center
      = f.submit 'Send & Register', class: 'button btn_cta', name: 'deliver[deliver]'
      / a.button.btn_cta href='#{@choice_collection.id}/deliver' title='Send Choice Collection via Email and Register' Send & Register
      | &nbsp; &nbsp;
      span.break_box
        / a.button href='#{@choice_collection.id}/deliver?collection_only=true' title='Send Choice Collection via Email to the User without Registering at these Properties' 
        = f.submit 'Send to User Only', name: 'deliver[collection_only]'
        | &nbsp; &nbsp;
        = f.submit 'Register Only', name: 'deliver[registration_only]'
        / a.button href='#{@choice_collection.id}/deliver?registration_only=true' title='Register User at these Properties without Sending Choice Collection to the User' Register Only
     
  .clr

javascript:
  $(function(){
    setTimeout(function(){
      $('.redactor_btn_italic, .redactor_btn_deleted, .redactor_separator, .redactor_btn_image, .redactor_btn_video, .redactor_btn_table').hide();
      $('.redactor_box').find('p').each(function(){
        if ( $(this).text() == '' )
          $(this).remove()
      });
    }, 1000);
  });
  